### ISSUE TITLE
Website not reachable from Chrome

### ISSUE THREAD

**Issue by jhsware** [infernojs/inferno-website#110]
https://infernojs.org is getting `ERR_CONNECTION_REFUSED` on Chrome 65 (macOS) and also not reachable with Safari. Mobile Safari refuses and says: “Safari can’t open the page because a secure connection couldn’t be established”

DOES WORK on Firefox 58 (macOS)

I am guessing there is an issue with the SSL certificate.

**Comment by Havunen** [comment]
@nightwolfz @LukeSheard Can you check this out?

**Comment by allanbreyes** [comment]
I'm seeing this behavior as well. FWIW, it looks like it's still loading from the service worker okay, so at least that's working! Have you considered using something like CloudFlare for coverage? I believe [it's free for open source](https://blog.cloudflare.com/cloudflare-open-source-your-upgrade-is-on-the-house/)

**Comment by jhsware** [comment]
I can confirm that it only worked on Firefox because it was cached. When loading in a private session it is broken.

**Comment by jhsware** [comment]
Fixed by @nightwolfz, apparently Nginx had gone to sleep
