### ISSUE TITLE
Docs are broken. All text replaced with [object Object]

### ISSUE THREAD

**Issue by calebmer** [infernojs/inferno-website#115]
<img width="1680" alt="screen shot 2018-04-18 at 7 40 59 pm" src="https://user-images.githubusercontent.com/8282507/38968473-795373b6-4340-11e8-9f35-bb2918dd400b.png">

https://infernojs.org/docs/guides/installation

**Comment by deamme** [comment]
Please try to clear your cache.

**Comment by calebmer** [comment]
It’s better now 😊
