### ISSUE TITLE
Error in documentation

### ISSUE THREAD

**Issue by daniel12fsp** [infernojs/inferno-website#117]
I have tested every link in inferno documentation and the same error happened it.

Site:https://infernojs.org/docs/guides/event-handling

![infernojs org_docs_guides_event-handling ipad pro](https://user-images.githubusercontent.com/6710830/40675615-376da3b0-6346-11e8-8a8f-c95cc751ce32.png)

**Comment by daniel12fsp** [comment]
It's working now.

**Comment by deamme** [comment]
Great!
