### ISSUE TITLE
Does not seem to work with www

### ISSUE THREAD

**Issue by justinas** [infernojs/inferno-website#142]
While https://infernojs.org/ (no-www) works, https://www.infernojs.org/ currently produces a 404 from Zeit.
![image](https://user-images.githubusercontent.com/662666/71617394-864c8400-2bc3-11ea-8cb1-c285978229e6.png)

**Comment by Havunen** [comment]
@aretecode Do you know what could cause this behavior?

**Comment by aretecode** [comment]
@Havunen https://zeit.co/docs/v2/custom-domains?query=www#redirecting-domains

**Comment by Havunen** [comment]
fixed
