### ISSUE TITLE
The JS Fiddle link does not work

### ISSUE THREAD

**Issue by devmoksh** [infernojs/inferno-website#152]
On the website, the JS Fiddle link doesn't work: [Link](https://jsfiddle.net/xo5jfe64/)

**Comment by devmoksh** [comment]
I was investigating this bug and I found that in the console it logs out '"<a class='gotoLine' href='#88:10'>88:10</a> Uncaught SyntaxError: Unexpected token '&lt;'"', then it says '"Script error."' and also, if I select Inferno in the frameworks and extensions, then it works 🤷‍♀️.

**Comment by Havunen** [comment]
JSFiddle changes quite often how the scripts are referenced and this causes issues to our babel plugin :(
