### ISSUE TITLE
Docs Inaccessible

### ISSUE THREAD

**Issue by domexie** [infernojs/inferno-website#172]
when deployed locally, I get 404:Cannot GET /docs/guides/installation
when visiting https://www.infernojs.org/docs/guides/installation, I get Vercel error:
404: NOT_FOUND
Code: NOT_FOUND
ID: hnd1::rggg6-1685347764792-cc197e464688

**Comment by alectrocute** [comment]
Completely broken for me.

<img width="1415" alt="Screenshot 2023-06-02 at 8 10 46 AM" src="https://github.com/infernojs/inferno-website/assets/35377827/30aaea30-0732-4c57-8958-4c9d8764091c">

**Comment by miguelpduarte** [comment]
Same here, tested on Firefox and Chrome

**Comment by Havunen** [comment]
Its fixed now, thanks for reporting the issue!
