### ISSUE TITLE
Hydration issue between server and client

### ISSUE THREAD

**Issue by ddibiase** [infernojs/inferno-website#25]
I just updated the Getting Started link on the homepage to the docs at URL `http://localhost:8080/docs/guides/getting-started.md`. When testing the link I noticed that hitting the page threw an error:
```
Uncaught Error: Inferno Error: failed to hydrate. The server-side render doesn't match client side.
```
Seems like a potential inferno-server issue but cannot confirm right now.

**Comment by nightwolfz** [comment]
You should be using a `Link` there, let me know if you still see the issue

**Comment by ddibiase** [comment]
It also happens if you hit the page directly and attempt clicking refresh.

**Comment by nightwolfz** [comment]
@ddibiase
You mean going directly to https://beta.infernojs.org/docs/guides/getting-started.md and refreshing ?

I don't see it....

**Comment by ddibiase** [comment]
It's not happening on the live site, but was happening locally. I really think it's a hot loading issue.

**Comment by ddibiase** [comment]
Fixed by @trueadm
