### ISSUE TITLE
Alternatives to JSX : createElement content missing

### ISSUE THREAD

**Issue by h2oboi89** [infernojs/inferno-website#34]
https://github.com/infernojs/inferno-website/blob/master/src/docs/guides/alternatives-to-jsx.md#createelement

Header exists, but no content

**Comment by trueadm** [comment]
Thanks for this, we clearly completely missed this when writing the docs! We'll get it sorted ASAP!

**Comment by ddibiase** [comment]
@h2oboi89 sorry for missing that. We just pushed a change to the website. Let us know if you find anything else!
