### ISSUE TITLE
JS benchmark chart is misleading

### ISSUE THREAD

**Issue by Zalastax** [infernojs/inferno-website#38]
The chart is cut of at the left, making the difference seem more extreme than it really is. Ember is not five times slower than inferno in the benchmark but it looks like it is in the chart.
![image](https://cloud.githubusercontent.com/assets/908496/21680780/27d24946-d34c-11e6-83e4-f528f5eb48d4.png)

**Comment by Zalastax** [comment]
@trueadm The component in itself looks correct and the site looks beautiful. I'm looking forward to using inferno in the future.
The problem is in the manually calculated values on https://github.com/infernojs/inferno-website/blob/b70aa0cd40b8f68e0d8f86cb4e90b30519efa1c3/src/components/home/Benchmarks.js#L23-L28. Vanilla JS gets the value 0.1 so it's very short for its score. The pattern for all of the frameworks is that `value = 0.1 + (score - 1)`, except for infernojs with a value of `0.14` where I expected `0.104` (so it's actually bigger than expected). A better value function is to not cut the lower part of the score: `value = score / 1.64`. I can make a PR with either the scores recalculated or the component updated to automatically scale based on `Math.max(...data.map(v => v.score))` if you want.

**Comment by trueadm** [comment]
Ah so there was a bug! A PR would be awesome thanks :)

**Comment by Havunen** [comment]
Also it would be nice to get new benchmark with latest versions of all libs
