### ISSUE TITLE
Share.png image's speedometer only shows moderate speed

### ISSUE THREAD

**Issue by jerairrest** [infernojs/inferno-website#40]
The meta image (https://www.infernojs.org/assets/share.png) that gets shared has a different speedometer that shows an inconsistent speed compared to the one on the actual website.

**Comment by ddibiase** [comment]
Haha, thanks for pointing that out. We modified the asset on the website but not share. I'll adjust it now. =)

**Comment by jerairrest** [comment]
Thanks! :)

**Comment by ddibiase** [comment]
Fixed!
