### ISSUE TITLE
Case studies and examples of Inferno in userland

### ISSUE THREAD

**Issue by davedbase** [infernojs/inferno-website#41]
@mikelawrence and I are planning to create a Tutorials/Examples section. A design is being worked on right now and coding shouldn't take much effort now that 1.0 is released.

**Comment by miketlawrence** [comment]
Mock for the a basic starter landing page.
![example-basic-mock-v2](https://cloud.githubusercontent.com/assets/10500655/22428241/eab294d8-e6cb-11e6-96dd-2068d3fc7d76.jpg)

**Comment by ddibiase** [comment]
Looks good @miketlawrence. Let's get some feedback from the community and then push it into production. We also need to start collecting examples to populate this page with.

**Comment by Havunen** [comment]
Are there any news regarding this task? There are some people willing to share their cases

**Comment by rafaelkallis** [comment]
stupid simple reddit client using inferno, redux and brunch:

https://github.com/rafaelkallis/inferno-example-reddit-client

<img width="755" alt="screen shot 2017-03-11 at 18 02 42" src="https://cloud.githubusercontent.com/assets/9661903/23825171/fbc581e4-0684-11e7-8c2d-a2de7f32face.png">

**Comment by Havunen** [comment]
Hi!

We have built large CRM / financial / work management software using inferno. 

link to free 30 days trial: 
https://severa.visma.fi/registration/?pricingModel=business&lang=en

**Comment by Jhony-Reyes** [comment]
A github page with inferno implementation for a basic app of data representation

https://jhony-reyes.github.io/melp/
