### ISSUE TITLE
i18n support for website and documentation copy

### ISSUE THREAD

**Issue by davedbase** [infernojs/inferno-website#42]
Hi everyone, we will need support translating the Inferno site and documentation into multiple languages. I can commit to Italian and I think @nightwolfz can handle French, Dutch and Russian apparently.

**Comment by ddibiase** [comment]
Had a discussion with @longho on Slack and it would be fantastic if we can get a module port of `react-intl` to `inferno-intl` that would act as a fantastic utility for the website and port a very useful module to the Inferno project as a whole.

**Comment by guuibayer** [comment]
Hi @ddibiase, I can contribute with the translation to brazilian portuguese 😄

**Comment by diegochavez** [comment]
Hi, support on spanish here!

**Comment by FQ400** [comment]
Hey, I can offer german.

**Comment by LukeSheard** [comment]
@FQ400 @diegochavez @guuibayer It could be great if you could help by translating the content in here (https://github.com/infernojs/inferno-website/tree/translations/src/docs/en) into an appropriately labelled folder! I can work on integrating them together.

**Comment by FQ400** [comment]
I translated 50% of `docs/api` to german. See: [my commit](https://github.com/FQ400/inferno-website/commit/719835b4b5d09856f9d0af7ec3a0c09eeb099c1f)

I am at `inferno-server`.

What does the following mean: [Link to english version](https://github.com/infernojs/inferno-website/blame/master/src/docs/api/inferno-server.md#L14). I don't get it. :(

```
If `Inferno.render()` is called on a string send using this method then Inferno will only attach hooks to the DOM increasing performance on the initial render.
```

@ddibiase can you help me out?

**Comment by FQ400** [comment]
@LukeSheard I am done with the german translation of [`docs/de/api/`](https://github.com/FQ400/inferno-website/tree/translations/src/docs/de/api). 

How would you like to continue? Against which branch you like to have the PR?

**Comment by LukeSheard** [comment]
@FQ400 Let's merge everything into the translations branch and I'll start thinking how we manage the different languages 👍

**Comment by Insidebox** [comment]
I can offer French

**Comment by MrFoxPro** [comment]
I think https://www.npmjs.com/package/inferno-i18next can be useful

**Comment by Havunen** [comment]
Keeping the website only english for now, to reduce maintenance work
