### ISSUE TITLE
404 when accessing guide directly

### ISSUE THREAD

**Issue by yihongang** [infernojs/inferno-website#48]
e.g. https://infernojs.org/docs/guides/installation

not sure if this is the right place as it looks like an nginx config issue?

**Comment by ddibiase** [comment]
Hi, yeah we had some trouble last evening. A PR was submitted that I accepted on mobile, the developer added a line break in an array and I didn't notice it on my small device.

So it was accepted and took down the server which doesn't have boot recovery yet. We just pushed it back live.

For those wondering this had nothing to do with Inferno. Just a silly PR and core team members didn't all have access yet to the server.

It's back now and we're hardening the system for better recovery in these situations.
