### ISSUE TITLE
Use latest Inferno version

### ISSUE THREAD

**Issue by Havunen** [infernojs/inferno-website#52]
Inferno now exposes `Inferno.version` which is version of currently installed module. We could use that number to keep docs up to date with Inferno version.

Website currently is refering to Inferno 1.0.3 Should be 1.1.2 (by the time of writing this issue)

**Comment by ddibiase** [comment]
The version number has been implemented on the site itself. Homepage, footer and docs now all reference the same version value propagated by the installed version on the site.

In markdown a shortcode [version] is replaced on request from the docs API.
