### ISSUE TITLE
Add brunch guide

### ISSUE THREAD

**Issue by rafaelkallis** [infernojs/inferno-website#59]
In addition to the new [brunch-with-inferno](https://github.com/infernojs/brunch-with-inferno), it would be great to have a new guide for the docs, as requested in [this issue](https://github.com/infernojs/inferno/issues/708).

Will open a pull request as soon as I create the md.

**Comment by ddibiase** [comment]
I added the link as Brunch Builder and put the copy that you supplied on Slack at the top.

Thanks again!
