### ISSUE TITLE
Docs view

### ISSUE THREAD

**Issue by miketlawrence** [infernojs/inferno-website#6]
Hello everyone!

I saw Dominic's tweet, joined the Slack team and here I am.

I was going to take a crack at the Docs view, unless there is a reason not to. Probably do some rough mocks in Sketch to post on the Slack channel.

Let me know if my time would be better spent on a different view.

Also let me know if we've chosen any specific approach to grids, em/rem/px, etc...

Thanks!

**Comment by trueadm** [comment]
@miketlawrence this sounds great. I believe @LukeSheard was working on the `docs` already (they are currently on the main Inferno repo, but we need to migrate them over to this repo). He might be able to help you out.

In regards to grids, I believe the best people to speak to are @nightwolfz, @dblaise and @ivanheral

**Comment by ddibiase** [comment]
I'm going to close this as the docs are integrated but there are other subtle issues associated with it now.
