### ISSUE TITLE
Compiler error on frontpage example

### ISSUE THREAD

**Issue by bildsoe** [infernojs/inferno-website#62]
I get a "Compiler Error: require is not defined" on your frontpage example.

Perhaps fix it? :)

**Comment by ddibiase** [comment]
Sorry? Where are you seeing this error exactly?

**Comment by Havunen** [comment]
What example exactly?

**Comment by OsmanMesutOzcan** [comment]
The error is on the home page. says `Compiler Error: require is not defined`. 
 I use google chrome Version 55.0.2883.95 (64-bit). If it is any help

**Comment by bildsoe** [comment]
On the landing page of your site - the example at the bottom of the page. I ude the same version of Chrome as mentioned in the above comment

**Comment by Havunen** [comment]
Thanks for reporting, there was issue with babel-plugin-inferno.
