### ISSUE TITLE
[Question]: Link to Incompose (recompose clone)

### ISSUE THREAD

**Issue by zanettin** [infernojs/inferno-website#67]
Hi

I've created a clone of recompose for inferno and thought it could be interesting for some of your users. Maybe in the (functional) component section of your [website](https://infernojs.org/docs/guides/components)?

Incompose: https://github.com/zanettin/incompose

If you agree, I could create a PR for this. Just let me know what you think about it.

**Comment by Havunen** [comment]
Hi @zanettin sounds good to me 👍

**Comment by zanettin** [comment]
Nice, thx 😄 
Do I need to fork to create the PR or can you give me access rights to push it in a new branch?
