### ISSUE TITLE
page not found / HTML5 history problems

### ISSUE THREAD

**Issue by szkrd** [infernojs/inferno-website#80]
Maybe it's just me, don't know, but whenever I navigate to a page in the docs section (for example [here](https://infernojs.org/docs/api/inferno-router)) and reload the tab (or just reopen the browser) I get a "not found" message - probably the site has no server side renderer/router, would it be possible to switch to hash or hashbang style "legacy" urls? Wouldn't that help? Thanks!

**Comment by Havunen** [comment]
https://github.com/infernojs/inferno/issues/987
