### ISSUE TITLE
Perf comparison: The Mitrhil vdom-benchmark score is 2 years out of date

### ISSUE THREAD

**Issue by pygy** [infernojs/inferno-website#84]
See https://cdn.rawgit.com/pygy/vdom-benchmark-mithril/87d3c48aca722ed24a62b31ca48639a82c413022/index.html for v1.1.1 which is 2-3 times slower than Inferno, depending on the browser used, not 6 or 10 times like v0.2.0.

(paste the above url in the "custom" field in https://vdom-benchmark.github.io/vdom-benchmark/)

**Comment by farooqkz** [comment]
I don't think this is valid anymore.
