### ISSUE TITLE
Can not resolve infernojs.org

### ISSUE THREAD

**Issue by dhdemerson** [infernojs/inferno-website#95]
The [infernojs.org](https://infernojs.org) website appears to be down and unreachable.

**Comment by Havunen** [comment]
DNS was down. It should work now

**Comment by dhdemerson** [comment]
Could just be slow propagation, but still looks down to me.

**Comment by Havunen** [comment]
Yeah its down again, our server is running but DNS is not responding. :( 

@nightwolfz 

Probably we should change DNS provider? @trueadm

**Comment by trueadm** [comment]
I control the domain still, so if someone wants me to point the domain at a different set of nameservers – let me know.

**Comment by dhdemerson** [comment]
Seems like this is resolved? Leaving this open for any necessary followup discussion.

**Comment by Havunen** [comment]
Yeah dominic fixed the DNS. The new website is now there. Lets close this :)
