### ISSUE TITLE
Include release information!

### ISSUE THREAD

**Issue by Havunen** [infernojs/inferno-website#96]
Hi,

It would be nice to have release information in our website!

Maybe we could highlight latest release in the main page and then have separate view for whole release history.  Currently the release information is stored in Github and we should fetch it from there, because I don't want to maintain two places. 

See:  https://github.com/infernojs/inferno/releases?after=v4.0.0-2

Some options:

Option 1: We could load release information from Github, using our server as proxy so it would parse markdown same way as docs, but this would make extra traffic to our server

Option 2: We could load release information from Github and parse the markdown syntax at client. But then we need to include that big chunk of JS to client side.

Option 3: We setup webhooks to Github and preload all releases into some json file on our server and then use it same way as api/docs

Other ideas are also welcome.

**Comment by deamme** [comment]
Option 3 is definitely the most optimal solution. Should there be a new menu item for `releases` or where should the release history be?

**Comment by Havunen** [comment]
Yeah new menu item would be nice and then maybe the latest release could be on The main page
