### ISSUE TITLE
If you have built inferno utility please add link and short description about it

### ISSUE THREAD

**Issue by Havunen** [infernojs/inferno-website#99]
There is now utilities section in our website! 

https://github.com/infernojs/inferno-website/blob/master/src/docs/guides/utilities.md

You can add the thing you have built for inferno there.
Also send PR to add it to inferno main repository readme.

**Comment by jhsware** [comment]
Does any Inferno-library count? I would like to add inferno-bootstrap once I have verified that it works well with Inferno 4

**Comment by Havunen** [comment]
Yeah! Sounds good

**Comment by tamb** [comment]
Is this issue still active?

**Comment by Havunen** [comment]
Don't think so, lets close .)
